version: '3'
services:
  app:
    build: .
    container_name: 'node-app'
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
    volumes:
      - ${PWD}:/app/server
    working_dir: /app/server
  db:
    container_name: 'database-bands-node'
    image: mariadb:10.5.9-focal
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo